### ISSUE TITLE
IAssemblyScanner Missing reference.

### ISSUE THREAD

**Issue by DotNetExecution** [structuremap/structuremap.dnx#5]
Hi, I don't think this is a problem with the package it self, but feel like I must ask.

I have problems building my DNX (1.0.0-rc2-15546) class library using your package (0.4.0-alpha4)
This is the code i am using that renders this error:

Everything looks correct and all assembly's seems to be in place, so i cant really figure out wye this happens.

>C:\Users\Stefan\Documents\visual studio 2015\Projects\Successful\Successful.Core\Successful.Core.Ioc\Modules\PlanrModule.cs(12,22): .NETPlatform,Version=v5.4 error CS1061: 'IAssemblyScanner' does not contain a definition for 'TheCallingAssembly' and no extension method 'TheCallingAssembly' accepting a first argument of type 'IAssemblyScanner' could be found (are you missing a using directive or an assembly reference?)

```C#
namespace Successful.Core.Ioc.Modules
{
    public class PlanrModule : Registry, IPlanrModule
    {
        public PlanrModule()
        {
            Scan(scan =>
            {
                scan.TheCallingAssembly();
                scan.WithDefaultConventions();
            });
            // Specific implementation comes here.
        }
    }
}
```

```json
  "frameworks": {
    "net451": { },
    "dotnet5.4": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-23516",
        "System.Collections": "4.0.11-beta-23516",
        "System.Linq": "4.0.1-beta-23516",
        "System.Runtime": "4.0.21-beta-23516",
        "System.Threading": "4.0.11-beta-23516"
      }
    }
  },
  "dependencies": {
    "StructureMap.Dnx": "0.4.0-alpha4"
  }
```

**Comment by khellang** [comment]
Did you add `using StructureMap.Graph;`? `TheCallingAssembly` is an extension method in that namespace.

**Comment by khellang** [comment]
Also, I wouldn't go much further than `-rc1-final` using this package. It's built against RC1, so there's no guarantees it will work with newer bits. Just sayin' :smile:

**Comment by DotNetExecution** [comment]
Ty for your reply, yes i have added the using statement and i am able to go into that assembly. 
Ill try to point to RC1 but i really don't think the problem is with the lib.

Ill try and will tell you the result when its done.

**Comment by khellang** [comment]
No, I doubt *this* problem is with the lib, but there might be others. As I said;

> It's built against RC1, so there's no guarantees it will work with newer bits.

**Comment by jeffogata** [comment]
I see the same error using rc1-update1.  Looks like `AssemblyScannerExtensions` is in the `StructureMap.Net4` project only;  I am guessing none of those methods are available to us in DNX.    `AssemblyContainingType<T>` can be used in DNX, so you might consider that instead.

**Comment by khellang** [comment]
This has nothing to do with this adapter. If you're having trouble using SM with DNX, I suggest you file issues in the main SM repository.
