### ISSUE TITLE
Setter Injection does not work in controllers

### ISSUE THREAD

**Issue by rguerreiro** [structuremap/structuremap.dnx#6]
The `[SetterProperty]` attribute inside a controller does not work. .

After running the `container.Populate(services)` the build plan for the controller shows nothing (in terms of properties), unless I explicitly add the controller to the container (eg: `For<HomeController>().Use<HomeController>()`). When I do that, the property is injected. In my mind, I shouldn't need to do this. Perhaps the service provider could call `BuildUp()` when getting a controller instance?

Am I doing anything wrong or this is, in fact, a bug?

**Comment by khellang** [comment]
Can you post the `ConfigureServices` code? I mostly consider property injection an anti-pattern and have never used it, so I'm not 100% on how it works with StructureMap. Are you sure your controllers are retrieved from the SM container?

**Comment by rguerreiro** [comment]
Here's the code for my `ConfigureServices` method:
```
// Add EF services to the services container
services.AddEntityFramework()
    .AddSqlServer()
    .AddDbContext<ApplicationDbContext>(options =>
        options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"]));

// Add Identity services to the services container
services.AddIdentity<ApplicationUser, IdentityRole>(options => 
{
    options.Cookies.ApplicationCookie.AccessDeniedPath = "/Home/AccessDenied";
    options.User.RequireUniqueEmail = true;
})
    .AddRoleManager<ApplicationRoleManager>()
    .AddEntityFrameworkStores<ApplicationDbContext>()
    .AddDefaultTokenProviders();

// Add MVC services to the services container
 services.AddMvc();

  // Configure Auth
services.AddAuthorization(options =>
{
    options.AddPolicy("UserVerified",
        authBuilder => { authBuilder.RequireClaim("UserVerified", "True"); });
});

// Bootstrapping StructureMap
var container = new Container(_ => 
{
    _.Scan(x =>
    {
        x.AssemblyContainingType<Startup>();
        x.WithDefaultConventions();
        x.LookForRegistries();
    });
});

container.Populate(services);

return container.GetInstance<IServiceProvider>();
```
You can find all you need about property injection with StructureMap [here](http://structuremap.github.io/setter-injection/). And although I agree with you with it being an anti-pattern, it's acceptable in some cases.

**Comment by jeremydmiller** [comment]
@rguerreiro @khellang I'll confirm the behavior in SM itself this morning, but I don't know how the build plan determination would be any different. In the meantime, are you sure that in the case of the non-explicit configuration that StructureMap itself is building the Controller object?

**Comment by jeremydmiller** [comment]
@rguerreiro @khellang This test passes in the 4.0.1 master branch:

```
    [TestFixture]
    public class Concrete_types_with_settable_property
    {
        [Test]
        public void gets_the_setter_policies_applied()
        {
            var container = new Container(_ =>
            {
                _.For<IFoo>().Use<Foo>();
            });

            var guy = container.GetInstance<GuyWithSetter>();

            guy.FooThing.ShouldBeOfType<Foo>();
        }

        public interface IFoo { }
        public class Foo : IFoo { }

        public class GuyWithSetter
        {
            [SetterProperty]
            public IFoo FooThing { get; set; }
        }
    }
```

And the build plan was:

PluginType: StructureMap.Testing.Bugs.Concrete_types_with_settable_property+GuyWithSetter
Lifecycle: Transient
new GuyWithSetter()
Set IFoo FooThing = **Default**

I've got nothing here.

**Comment by khellang** [comment]
Ah, I figured it out! This looks like it's related to how MVC handles controller activation. MVC doesn't treat controllers as "services" by default.
This means that it won't ask the `IServiceProvider` for controllers. If you want to add the controllers to the container as "services", you need to call `AddControllersAsServices`:

```csharp
services.AddMvc()
    .AddControllersAsServices(new []
    {
        typeof(Startup).GetTypeInfo().Assembly
    });
```

**Comment by rguerreiro** [comment]
@jeremydmiller yes I knew that the problem wasn't with SM itself, in terms of injecting the property. It had to be with the StructureMap.Dnx or with the MVC. To bypass this problem I used the `[FromServices]` attribute from the MVC framework.

@khellang Your solution works fine. Just as expected. Perhaps this is something that you could put in the docs.

Thanks guys for all the help. I'm closing the issue now.

**Comment by khellang** [comment]
> Perhaps this is something that you could put in the docs.

I'm a bit reluctant to put this in the docs, since it turned out to be unrelated to this adapter. It could set a bad precedent...

**Comment by rguerreiro** [comment]
@khellang yes I know that it's unrelated but if one is trying to use the full blown capabilities of StructureMap (coff property injection coff), has no other option but to call the `AddControllersAsServices` method. If that isn't in the docs, how one would know about it? ;)

You could put it like a **pro tip** comment. But it's up to you. It was just a suggestion

**Comment by jeremydmiller** [comment]
@rguerreiro @khellang We could have the DNX adapter slap something in that tells SM to auto-register concrete types of Controller when somebody asks for them the first time. The only reason that isn't quite working now is that MVC6 gets things through `TryGetInstance` instead of `GetInstance`. You *could* change the StructureMapServiceProvider to use GetInstance(type) if you're requesting a concrete type to force SM to create a build plan and implicit registration for the Controller types.

**Comment by khellang** [comment]
> If that isn't in the docs, how one would know about it? ;)

@rguerreiro Read the MVC docs? :grin: This repo has nothing to do with MVC. It's an important distinction. It can be used with any other framework. The way the framework calls the adapter is not up to us to document. It's a slippery slope if we start to documenting different frameworks behaviours. You should file an issue in the MVC repo, telling them to provide better documentation. If you ask me, it's a really weird thing; having to call a method for the framework to ask the container for controllers.

> The only reason that isn't quite working now is that MVC6 gets things through `TryGetInstance` instead of `GetInstance`.

@jeremydmiller Not really. MVC doesn't even ask the container for the controller type itself. It only asks for the controllers dependencies -- if it has any. By default, it uses the [`DefaultControllerActivator`](https://github.com/aspnet/Mvc/blob/1f8744209263f1c93caec4157b0fa804d99d2e82/src/Microsoft.AspNet.Mvc.Core/Controllers/DefaultControllerActivator.cs), which simply calls a cached compiled lambda (see [`ActivatorUtilities`](https://github.com/aspnet/Common/blob/e9de858fbbc5a26f8ef1906028b67361708e97aa/src/Microsoft.Extensions.ActivatorUtilities.Sources/ActivatorUtilities.cs)).

If you want MVC to actually ask the container for the controllers, you need to call `AddControllersAsServices` , which registers all controller types (in a specified collection or assemblies), and then swaps out the `IControllerActivator` service with the [`ServiceBasedControllerActivator`](https://github.com/aspnet/Mvc/blob/1f8744209263f1c93caec4157b0fa804d99d2e82/src/Microsoft.AspNet.Mvc.Core/Controllers/ServiceBasedControllerActivator.cs) (see [`ControllersAsServices`](https://github.com/aspnet/Mvc/blob/1f8744209263f1c93caec4157b0fa804d99d2e82/src/Microsoft.AspNet.Mvc.Core/Internal/ControllersAsServices.cs). Again, this will call `TryGetInstance`, but I'm not sure that's a big deal.

I'd rather not do any magic in this library, coupling it to MVC, because it's equally as usable with any other framework (not only web) :smile:

**Comment by jeremydmiller** [comment]
@khellang Pfft, okay. That's just making me want to get Jasper going faster now.

**Comment by khellang** [comment]
:stuck_out_tongue_closed_eyes:

**Comment by rguerreiro** [comment]
Hi @khellang it's me again :)

I'm upgrading a project from RC1 to 1.0 and this issue appeared again (properties with `[SetterProperty]` aren't being initialized from the container), but this time I'm definitely calling the `AddControllersAsServices` method. Can you check if it's something related to StructureMap.Dnx or with MVC itself?

Here's the my `ConfigureServices` method:
````
public IServiceProvider ConfigureServices(IServiceCollection services)
{
	// Get options
	services.AddOptions();
	services.Configure<ConfigOptions>(Configuration);

	// Add framework services.

	// Add EF services to the services container
	services.AddDbContext<ApplicationDbContext>(options =>
		options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));

	// Add Identity services to the services container
	services.AddIdentity<ApplicationUser, IdentityRole>(options => 
		{
			options.Cookies.ApplicationCookie.CookieName = ".auth";
			options.Cookies.ApplicationCookie.AccessDeniedPath = "/Error/AccessDenied";
			options.User.RequireUniqueEmail = true;
		})
		.AddRoleManager<ApplicationRoleManager>()
		.AddEntityFrameworkStores<ApplicationDbContext>()
		.AddDefaultTokenProviders();

	// Add MVC services to the services container
	services.AddMvc()
		.AddJsonOptions(options =>
		{
			options.SerializerSettings.DateTimeZoneHandling = Newtonsoft.Json.DateTimeZoneHandling.Utc;
		})
		.AddControllersAsServices();

	// Add the localization services to the services container
	services.AddLocalization(options => options.ResourcesPath = "Resources");

	// Configure supported cultures and localization options
	services.Configure<RequestLocalizationOptions>(options =>
	{
		var supportedCultures = new[]
		{
			new CultureInfo("en-US"),
			new CultureInfo("pt-PT")
		};
		options.SupportedCultures = supportedCultures;
		options.SupportedUICultures = supportedCultures;
	});

	// Configure Auth
	services.AddAuthorization(options =>
	{
		options.AddPolicy(
			"IsUserVerified",
			authBuilder => 
			{
				authBuilder.RequireClaim("UserVerified", "True");
			});
	});

	// Bootstrapping StructureMap
	var container = new Container();
	container.Configure(_ =>
	{
		_.Scan(x =>
		{
			//x.TheCallingAssembly();
			x.AssemblyContainingType<Startup>();
			x.WithDefaultConventions();
			x.LookForRegistries();
			x.AddAllTypesOf<IStartupTask>();
		});

		// adding asp.net already configured services
		_.Populate(services);
	});

	// executing some startup tasks
	var startupTasks = container.GetAllInstances<IStartupTask>();
	Parallel.ForEach(startupTasks, currTask => currTask.Execute());

	return container.GetInstance<IServiceProvider>();
}
```

**Comment by rguerreiro** [comment]
One thing that might help discovering what's going on is that the property isn't being injected if it's in a base class, like this one:
```
public class BaseController : Controller
{
    [SetterProperty]
    public IEmailSender EmailService { get; set; }
}
```
If the property is in the controller itself (eg: HomeController) it works. But on RC1 the `[SetterProperty]` worked even for the properties in the base class.

**Comment by rguerreiro** [comment]
It seems to be an issue with StructureMap itself. Here's the code to reproduce it:
```
public class MyRegistry : Registry
{
    public MyRegistry()
    {
        For<IMyService>().Use<MyService>();
        For<MyClass>().Use<MyClass>();
    }
}

public interface IMyService { }

public class MyService : IMyService { }

public class BaseClass
{
    [SetterProperty]
    public IMyService MyServiceInBaseClass { get; set; }
}

public class MyClass : BaseClass
{
    [SetterProperty]
    public IMyService MyServiceInMyClass { get; set; }
}

public class Program
{
    public static void Main(string[] args)
    {
        var container = new Container();
        container.Configure(_ =>
        {
            _.Scan(x =>
            {
                x.AssemblyContainingType<BaseClass>();
                x.WithDefaultConventions();
                x.LookForRegistries();
            });
        });

        var description = container.Model.For<MyClass>().Default.DescribeBuildPlan();
        Console.WriteLine(description);

        var myClass = container.GetInstance<MyClass>();
        Console.WriteLine(myClass.MyServiceInBaseClass == null ? "MyServiceInBaseClass is NULL" : "MyServiceInBaseClass is not NULL");
        Console.WriteLine(myClass.MyServiceInMyClass == null ? "MyServiceInMyClass is NULL" : "MyServiceInMyClass is not NULL");

        Console.ReadLine();
    }
}
```

It produces the following output:
```
PluginType: ConsoleApp1.MyClass
Lifecycle: Transient
new MyClass()
Set IMyService MyServiceInMyClass = **Default**

MyServiceInBaseClass is NULL
MyServiceInMyClass is not NULL
```
@jeremydmiller can you confirm? Do you prefer that I submit the issue in StructureMap rather than here?

**Comment by jeremydmiller** [comment]
Can you open this in StructureMap itself w/ a failing test? I'm on vacation sans computer, so it'll be Thursday at the earliest for me to look at it

**Comment by rguerreiro** [comment]
Here it is https://github.com/structuremap/structuremap/issues/490. It includes a new finding: it's related to StructureMap but only for .NET Core apps (the issue does not happen on .NET Framework)

**Comment by rguerreiro** [comment]
It's definitely a StructureMap issue. Closing this
