### ISSUE TITLE
StructureMap Profiles in DNX only honoured on first request

### ISSUE THREAD

**Issue by benfoster** [structuremap/structuremap.dnx#7]
I'm working on adding multi-tenant support to ASP.NET 5 and part of this involves overriding how `IServiceScope` is created.

We want to allow dependencies to be overridden for specific tenants and are using StructureMap profiles to do this.

I've taken the implementation of `IServiceScopeFactory` in this library and changed it to use a profile to create the request container:

        public IServiceScope CreateScope()
        {
            var profile = Container.GetProfile("TestProfile");
            return new StructureMapServiceScope(profile.GetNestedContainer());
        }

Everything else is pretty much the same. Unfortunately as you can see from this [repro](https://github.com/benfoster/StructureMapDnxProfileRepro) my profile configured dependency is only used on the first request - in this example we get `Guid.Empty` returned in the output and then it reverts back to the default implementation (returns `Guid.NewGuid()`).

Perhaps I've misunderstood profiles in StructureMap (or DI in ASP.NET 5)?

**Comment by khellang** [comment]
Are there any action items here? :smile:

**Comment by benfoster** [comment]
Sorry, it can be closed. I've not got round to adding StructureMap support for SaasKit yet but will need to send you a pull request so that we can override how the scope is created.
