### ISSUE TITLE
Target .Net 4.6/4.6.1 as well

### ISSUE THREAD

**Issue by DixonD-git** [structuremap/structuremap.dnx#8]
I need to use it for .Net 4.6.1 project which uses Microsoft.Extensions.DependencyInjection for DI abstraction

**Comment by khellang** [comment]
What errors did you get? The `net451` and `dotnet5.4` targets should both work perfectly fine with .NET 4.6.1 :smile:

**Comment by DixonD-git** [comment]
Trying to install via Nuget and get the following error:
```
Install-Package : Could not install package 'StructureMap.Dnx 0.3.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the 
package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

**Comment by khellang** [comment]
You need to make sure you're installing the pre-release version :smile:

**Comment by DixonD-git** [comment]
Yes, thanks, it works:) I should have been tried prerelease versions first :)
